import React from 'react';
import { Link } from 'react-router-dom';
import Loder from '../../../components/Loaders/loder/Loder';
import '../styles/Legal.scss';

const TermsAndConditions = () => {
  return (
    <div className="legal-page mesh-gradient-bg">
      <nav className="legal-navbar">
        <Link to="/" className="logo">
          <Loder size={28} color="#c7621a" />
          <span>jigyazaAi</span>
        </Link>
        <div className="nav-links">
          <Link to="/privacy">Privacy Policy</Link>
          <Link to="/login" className="back-link">Sign In</Link>
        </div>
      </nav>

      <main className="legal-container">
        <div className="legal-content glass-card custom-scrollbar">
          <h1>Terms and Conditions</h1>
          <p className="last-updated">Last updated: March 18, 2026</p>
          
          <div className="markdown-body">
            <h2>1. Agreement to Terms</h2>
            <p>These Terms and Conditions ("Terms") constitute a legally binding agreement between you ("you", "your", "User") and jigyazaAi Inc. ("jigyazaAi", "we", "our", "us") governing your access to and use of the jigyazaAi research engine, website, and all related products and services (collectively, the "Service").</p>
            <p>By creating an account, clicking "Sign up", "Sign in", or otherwise accessing or using our Service, you confirm that you have read, understood, and agree to be bound by these Terms and our Privacy Policy.</p>
            <p>If you do not agree to these Terms, do not use the Service.</p>

            <h2>2. Eligibility</h2>
            <p>To use jigyazaAi, you must be at least 16 years of age, have the legal capacity to enter into a binding agreement, not be prohibited from using the Service under applicable law, and not have had a previous account terminated by us for violating these Terms.</p>

            <h2>3. Account Registration</h2>
            <h3>3.1 Creating an Account</h3>
            <p>To access most features of the Service, you must create an account. You may register using your email address and a password, or via a supported OAuth provider (Google, GitHub).</p>

            <h3>3.2 Account Security</h3>
            <p>You are responsible for providing accurate information, keeping your password secure, all activity under your account, and notifying us immediately at support@jigyazaai.com if you suspect unauthorized access.</p>

            <h3>3.3 One Account Per User</h3>
            <p>You may not create multiple accounts for the same person. Accounts are personal and non-transferable unless explicitly permitted under a Teams or Enterprise plan.</p>

            <h2>4. Subscription Plans and Payments</h2>
            <p>jigyazaAi offers Free, Pro, and Teams plans. Paid plans are billed in advance on a recurring basis. All payments are processed by Stripe. We offer a 14-day money-back guarantee on Pro plan subscriptions for first-time subscribers. You may cancel your subscription at any time from your account settings.</p>

            <h2>5. Acceptable Use</h2>
            <h3>5.1 Permitted Use</h3>
            <p>You may use jigyazaAi solely for lawful purposes and in accordance with these Terms. The Service is intended for personal, educational, and professional research use.</p>

            <h3>5.2 Prohibited Conduct</h3>
            <p>You agree not to use the Service to violate any law, generate harmful content, infringe intellectual property, deceive or defraud, abuse the system, reverse engineer, overload infrastructure, harvest data, harm minors, or for competitive intelligence.</p>

            <h2>6. Intellectual Property</h2>
            <p>The Service is owned by or licensed to jigyazaAi Inc. You retain ownership of any content you submit to the Service. The answers and summaries generated by jigyazaAi are provided for your personal and professional use, acknowledging that they are AI-generated.</p>

            <h2>7. Third-Party Sources and Content</h2>
            <p>jigyazaAi fetches and summarizes content from third-party websites. We are not responsible for the accuracy, completeness, legality, or appropriateness of third-party content.</p>

            <h2>8. Disclaimer of Warranties</h2>
            <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, JIGYAZAAI EXPRESSLY DISCLAIMS ALL WARRANTIES.</p>
            <p>jigyazaAi is a research tool. Outputs should not be relied upon as professional legal, medical, financial, or other regulated advice.</p>

            <h2>9. Limitation of Liability</h2>
            <p>IN NO EVENT SHALL JIGYAZAAI BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE.</p>

            <h2>10. Indemnification</h2>
            <p>You agree to indemnify and hold harmless jigyazaAi Inc. from any claims arising out of your violation of these Terms, your User Content, or your use of the Service in violation of any applicable law.</p>

            <h2>11. API Access</h2>
            <p>If you access the Service via our API, your use is subject to these Terms and any additional guidelines we publish.</p>

            <h2>12. Termination</h2>
            <p>You may stop using the Service and delete your account at any time. We reserve the right to suspend or terminate your account if you violate these Terms.</p>

            <h2>13. Governing Law and Dispute Resolution</h2>
            <p>These Terms shall be governed by the laws of the jurisdiction in which jigyazaAi Inc. is incorporated. Any dispute shall be resolved through binding arbitration after a 30-day informal resolution period.</p>

            <h2>14. General Provisions</h2>
            <p>These Terms constitute the entire agreement between you and jigyazaAi. We may update these Terms from time to time, and will notify you of material changes.</p>

            <h2>15. Contact Us</h2>
            <p>
              <strong>jigyazaAi Inc.</strong><br/>
              Email: legal@jigyazaai.com<br/>
              Website: jigyazaai.com/terms
            </p>
          </div>
        </div>
      </main>
    </div>
  );
};

export default TermsAndConditions;
